name = "webhealthreport"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "webhealthreport"
database_id = "c379e50c-5790-46da-88fa-83c5b82ebeb0"

[vars]
AUTH0_DOMAIN   = "dev-fu1c3ghemmnxzhop.us.auth0.com"
AUTH0_AUDIENCE = "https://webhealthreport.pages.dev/api"
